### PR TITLE
Migrate to flutter 2.2 (null-safe)

### PR DESCRIPTION
**Pull request by zefhemel**
This still leaves some deprecated APIs, but at least it builds ands seems to work. Bonus: also adds a macOS app to the example (used that for testing).

Most of this work is done by the migration tool, but had to tweak a few things here and there. It's possible more things have been marked as non-nullable than should be, please check.

### CODE REVIEW

**Comment by mack-at-pieces** [comment]
Looking great! Excited to use this.

**Comment by mack-at-pieces** [comment]
hey @zefhemel we are trying to use this version in our app and are having problems getting the editor to build in Windows, Linux, and Android. We haven't tried iOS yet, but we are having success on MacOS so that's a good indicator. 

Our setup is fairly simple:
Screen Shot 2021-06-18 at 11 48 35 AM

The error isn't very descriptive, but this is what we're seeing:
Screen Shot 2021-06-18 at 11 54 34 AM


Any thoughts on what might be happening?

**Comment by sluebbert** [comment]
If it helps at all, this is the first exception dumped right before I too get the 'child == _child' error on android:

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#95e12](state: RawGestureDetectorState#f760f(gestures: <none>, excludeFromSemantics: true, behavior: opaque)):
Null check operator used on a null value

The relevant error-causing widget was
RichCodeField
When the exception was thrown, this was the stack
#0      _Editable.createRenderObject         :rich_code_editor/rich_editable_code.dart:1902
#1      RenderObjectElement.mount            :flutter/…/widgets/framework.dart:5430
...     Normal element mounting (75 frames)
#76     Element.inflateWidget                :flutter/…/widgets/framework.dart:3611
#77     Element.updateChild                  :flutter/…/widgets/framework.dart:3363
...
```

Seems like `Null check operator used on a null value` somewhere around `rich_editable_code.dart:1902` may be upsetting it.

**Comment by psovit** [comment]
Hi @zefhemel ,
Thanks for PR and my apologies for reviewing it so late.
Looks like lots of other changes have recently been added so I will have to review them, might consider creating a separate PR my self to support the latest Flutter changes.

**Pull request closed without merging**
